import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/site/layouts/app-sidebar";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react"
import Header from "@/components/site/layouts/hearder";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>

        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <Header />
            <Toaster />
            {children}
          </SidebarInset>
        </SidebarProvider>
        </SessionProvider>

      </body>
    </html>
  );
}
